### PR TITLE
Skip SMART info probes for reading serial number of the drive

### LINKED ISSUE #583: directpv process causing high load
this process causes load of about 30% of one core on pretty much all nodes.

```
directpv --identity=direct-csi-min-io -v=3 --endpoint=$(CSI_ENDPOINT) --node-id=n01 --dynamic-drive-handler
```

its log shows communication problems with etcd, if I get it right. Can that be the cause for the load? Ie. that it gets into a loop then?

I am aware my etcd is not the fastest:  is that a problem for directpv?

The load appears on almost all nodes, but not on all all the time. Some nodes have ZFS pools with lots of disks, all visible as zfs members  when listing drives. It also looks as if directpv constantly causes I/O on them -  why?  

the log from above process:
```
I0512 07:41:34.051187    3653 run.go:222] node server started
I0512 07:41:34.055144    3653 leaderelection.go:243] attempting to acquire leader lease direct-csi-min-io/n01-drive-controller...
I0512 07:41:34.055170    3653 leaderelection.go:243] attempting to acquire leader lease direct-csi-min-io/n01-volume-controller...
I0512 07:41:34.055195    3653 metrics.go:41] Starting metrics exporter in port: 10443
I0512 07:41:34.071338    3653 leaderelection.go:253] successfully acquired lease direct-csi-min-io/n01-drive-controller
I0512 07:41:34.071389    3653 listener.go:383] new leader detected, current leader: n01
I0512 07:41:34.071438    3653 listener.go:376] became leader, starting
I0512 07:41:34.071477    3653 listener.go:315] Starting drive controller
I0512 07:41:34.071548    3653 reflector.go:219] Starting reflector *v1beta4.DirectCSIDrive (1m0s) from k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167
I0512 07:41:34.071557    3653 reflector.go:255] Listing and watching *v1beta4.DirectCSIDrive from k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167
I0512 07:41:34.079724    3653 leaderelection.go:253] successfully acquired lease direct-csi-min-io/n01-volume-controller
I0512 07:41:34.079782    3653 listener.go:376] became leader, starting
I0512 07:41:34.079823    3653 listener.go:383] new leader detected, current leader: n01
I0512 07:41:34.080400    3653 listener.go:315] Starting volume controller
I0512 07:41:34.080437    3653 reflector.go:219] Starting reflector *v1beta4.DirectCSIVolume (1m0s) from k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167
I0512 07:41:34.080444    3653 reflector.go:255] Listing and watching *v1beta4.DirectCSIVolume from k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167
I0512 07:43:08.331905    3653 mount.go:70] "mounting device" device="/dev/sda3" target="/var/lib/direct-csi/mnt/5df578c9-6f6b-0a2c-5fb1-546cf7361a7a"
I0512 09:14:15.375146    3653 stage_unstage.go:39] "NodeStageVolumeRequest" volumeID="pvc-ae6af489-931c-4506-83d5-ed630cd4b624" StagingTargetPath="/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-ae6af489-931c-4506-83d5-ed630cd4b624/globalmount"
I0512 09:14:15.394287    3653 quota_linux.go:210] "SetQuota succeeded" Device="/dev/sda3" Path="/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-ae6af489-931c-4506-83d5-ed630cd4b624/globalmount" VolumeID="pvc-ae6af489-931c-4506-83d5-ed630cd4b624" ProjectID=1661858958 HardLimit=107374182400
I0512 09:14:15.465601    3653 publish_unpublish.go:84] "NodePublishVolumeRequest" volumeID="pvc-ae6af489-931c-4506-83d5-ed630cd4b624" stagingTargetPath="/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-ae6af489-931c-4506-83d5-ed630cd4b624/globalmount" containerPath="/var/lib/kubelet/pods/0e9f373e-6962-433b-94ad-4b760e500486/volumes/kubernetes.io~csi/pvc-ae6af489-931c-4506-83d5-ed630cd4b624/mount"
I0512 09:16:14.902729    3653 publish_unpublish.go:160] "NodeUnPublishVolumeRequest" volumeID="pvc-ae6af489-931c-4506-83d5-ed630cd4b624" ContainerPath="/var/lib/kubelet/pods/0e9f373e-6962-433b-94ad-4b760e500486/volumes/kubernetes.io~csi/pvc-ae6af489-931c-4506-83d5-ed630cd4b624/mount"
I0512 09:16:15.005171    3653 stage_unstage.go:128] "NodeUnstageVolumeRequest" volumeID="pvc-ae6af489-931c-4506-83d5-ed630cd4b624" StagingTargetPath="/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-ae6af489-931c-4506-83d5-ed630cd4b624/globalmount"
I0512 09:21:08.006485    3653 stage_unstage.go:39] "NodeStageVolumeRequest" volumeID="pvc-aac78719-2739-4b41-bee7-4ce0caea932f" StagingTargetPath="/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-aac78719-2739-4b41-bee7-4ce0caea932f/globalmount"
I0512 09:21:08.022691    3653 quota_linux.go:210] "SetQuota succeeded" Device="/dev/sda3" Path="/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-aac78719-2739-4b41-bee7-4ce0caea932f/globalmount" VolumeID="pvc-aac78719-2739-4b41-bee7-4ce0caea932f" ProjectID=343125013 HardLimit=107374182400
I0512 09:21:08.056096    3653 publish_unpublish.go:84] "NodePublishVolumeRequest" volumeID="pvc-aac78719-2739-4b41-bee7-4ce0caea932f" stagingTargetPath="/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-aac78719-2739-4b41-bee7-4ce0caea932f/globalmount" containerPath="/var/lib/kubelet/pods/50df0a60-89c2-4d31-ab6c-83778f21403b/volumes/kubernetes.io~csi/pvc-aac78719-2739-4b41-bee7-4ce0caea932f/mount"
I0512 09:28:27.765689    3653 publish_unpublish.go:160] "NodeUnPublishVolumeRequest" volumeID="pvc-aac78719-2739-4b41-bee7-4ce0caea932f" ContainerPath="/var/lib/kubelet/pods/50df0a60-89c2-4d31-ab6c-83778f21403b/volumes/kubernetes.io~csi/pvc-aac78719-2739-4b41-bee7-4ce0caea932f/mount"
I0512 09:28:27.867494    3653 stage_unstage.go:128] "NodeUnstageVolumeRequest" volumeID="pvc-aac78719-2739-4b41-bee7-4ce0caea932f" StagingTargetPath="/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-aac78719-2739-4b41-bee7-4ce0caea932f/globalmount"
I0512 10:36:48.709507    3653 stage_unstage.go:39] "NodeStageVolumeRequest" volumeID="pvc-79297077-6c4f-435d-a207-23fdc480f60e" StagingTargetPath="/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-79297077-6c4f-435d-a207-23fdc480f60e/globalmount"
I0512 10:36:48.728452    3653 quota_linux.go:210] "SetQuota succeeded" Device="/dev/sda3" Path="/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-79297077-6c4f-435d-a207-23fdc480f60e/globalmount" VolumeID="pvc-79297077-6c4f-435d-a207-23fdc480f60e" ProjectID=3396307691 HardLimit=107374182400
I0512 10:36:48.758500    3653 publish_unpublish.go:84] "NodePublishVolumeRequest" volumeID="pvc-79297077-6c4f-435d-a207-23fdc480f60e" stagingTargetPath="/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-79297077-6c4f-435d-a207-23fdc480f60e/globalmount" containerPath="/var/lib/kubelet/pods/577a59b0-e349-4338-8459-e27b95862be5/volumes/kubernetes.io~csi/pvc-79297077-6c4f-435d-a207-23fdc480f60e/mount"
I0512 10:48:56.373322    3653 publish_unpublish.go:160] "NodeUnPublishVolumeRequest" volumeID="pvc-79297077-6c4f-435d-a207-23fdc480f60e" ContainerPath="/var/lib/kubelet/pods/577a59b0-e349-4338-8459-e27b95862be5/volumes/kubernetes.io~csi/pvc-79297077-6c4f-435d-a207-23fdc480f60e/mount"
I0512 10:48:56.476207    3653 stage_unstage.go:128] "NodeUnstageVolumeRequest" volumeID="pvc-79297077-6c4f-435d-a207-23fdc480f60e" StagingTargetPath="/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-79297077-6c4f-435d-a207-23fdc480f60e/globalmount"
I0512 10:55:48.658230    3653 stage_unstage.go:39] "NodeStageVolumeRequest" volumeID="pvc-3cf0239f-ae29-4401-9041-0c985646c138" StagingTargetPath="/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-3cf0239f-ae29-4401-9041-0c985646c138/globalmount"
I0512 10:55:48.669668    3653 quota_linux.go:210] "SetQuota succeeded" Device="/dev/sda3" Path="/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-3cf0239f-ae29-4401-9041-0c985646c138/globalmount" VolumeID="pvc-3cf0239f-ae29-4401-9041-0c985646c138" ProjectID=4128920911 HardLimit=214748364800
I0512 10:55:48.707816    3653 publish_unpublish.go:84] "NodePublishVolumeRequest" volumeID="pvc-3cf0239f-ae29-4401-9041-0c985646c138" stagingTargetPath="/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-3cf0239f-ae29-4401-9041-0c985646c138/globalmount" containerPath="/var/lib/kubelet/pods/68d3603e-ab60-4230-9764-2ff6e68e4321/volumes/kubernetes.io~csi/pvc-3cf0239f-ae29-4401-9041-0c985646c138/mount"
I0512 10:55:58.517102    3653 publish_unpublish.go:84] "NodePublishVolumeRequest" volumeID="pvc-3cf0239f-ae29-4401-9041-0c985646c138" stagingTargetPath="/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-3cf0239f-ae29-4401-9041-0c985646c138/globalmount" containerPath="/var/lib/kubelet/pods/2fe196be-92fb-4c2b-b1cd-0eb122876bc5/volumes/kubernetes.io~csi/pvc-3cf0239f-ae29-4401-9041-0c985646c138/mount"
I0512 10:56:59.844263    3653 publish_unpublish.go:160] "NodeUnPublishVolumeRequest" volumeID="pvc-3cf0239f-ae29-4401-9041-0c985646c138" ContainerPath="/var/lib/kubelet/pods/2fe196be-92fb-4c2b-b1cd-0eb122876bc5/volumes/kubernetes.io~csi/pvc-3cf0239f-ae29-4401-9041-0c985646c138/mount"
I0512 11:29:47.986885    3653 stage_unstage.go:39] "NodeStageVolumeRequest" volumeID="pvc-bb17ec82-a02c-4a1f-ba42-537bef08070c" StagingTargetPath="/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-bb17ec82-a02c-4a1f-ba42-537bef08070c/globalmount"
I0512 11:29:47.999895    3653 quota_linux.go:210] "SetQuota succeeded" Device="/dev/sda3" Path="/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-bb17ec82-a02c-4a1f-ba42-537bef08070c/globalmount" VolumeID="pvc-bb17ec82-a02c-4a1f-ba42-537bef08070c" ProjectID=2651339000 HardLimit=214748364800
I0512 11:29:48.044689    3653 publish_unpublish.go:84] "NodePublishVolumeRequest" volumeID="pvc-bb17ec82-a02c-4a1f-ba42-537bef08070c" stagingTargetPath="/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-bb17ec82-a02c-4a1f-ba42-537bef08070c/globalmount" containerPath="/var/lib/kubelet/pods/655a1a10-6664-454c-8d88-4f8ccc9ea926/volumes/kubernetes.io~csi/pvc-bb17ec82-a02c-4a1f-ba42-537bef08070c/mount"
I0512 11:29:49.900516    3653 publish_unpublish.go:84] "NodePublishVolumeRequest" volumeID="pvc-bb17ec82-a02c-4a1f-ba42-537bef08070c" stagingTargetPath="/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-bb17ec82-a02c-4a1f-ba42-537bef08070c/globalmount" containerPath="/var/lib/kubelet/pods/25ad9876-1afd-4231-8357-228c0215ed2b/volumes/kubernetes.io~csi/pvc-bb17ec82-a02c-4a1f-ba42-537bef08070c/mount"
I0512 11:30:51.231114    3653 publish_unpublish.go:160] "NodeUnPublishVolumeRequest" volumeID="pvc-bb17ec82-a02c-4a1f-ba42-537bef08070c" ContainerPath="/var/lib/kubelet/pods/655a1a10-6664-454c-8d88-4f8ccc9ea926/volumes/kubernetes.io~csi/pvc-bb17ec82-a02c-4a1f-ba42-537bef08070c/mount"
I0512 11:33:37.425880    3653 publish_unpublish.go:84] "NodePublishVolumeRequest" volumeID="pvc-bb17ec82-a02c-4a1f-ba42-537bef08070c" stagingTargetPath="/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-bb17ec82-a02c-4a1f-ba42-537bef08070c/globalmount" containerPath="/var/lib/kubelet/pods/ace7697a-2d0f-4b19-85e5-8847ab622afe/volumes/kubernetes.io~csi/pvc-bb17ec82-a02c-4a1f-ba42-537bef08070c/mount"
I0512 11:34:38.677318    3653 publish_unpublish.go:160] "NodeUnPublishVolumeRequest" volumeID="pvc-bb17ec82-a02c-4a1f-ba42-537bef08070c" ContainerPath="/var/lib/kubelet/pods/ace7697a-2d0f-4b19-85e5-8847ab622afe/volumes/kubernetes.io~csi/pvc-bb17ec82-a02c-4a1f-ba42-537bef08070c/mount"
I0512 15:18:23.704895    3653 stage_unstage.go:39] "NodeStageVolumeRequest" volumeID="pvc-e7920393-a0e1-45cd-bd8f-1b1348a9ac51" StagingTargetPath="/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-e7920393-a0e1-45cd-bd8f-1b1348a9ac51/globalmount"
I0512 15:18:23.727643    3653 quota_linux.go:210] "SetQuota succeeded" Device="/dev/sda3" Path="/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-e7920393-a0e1-45cd-bd8f-1b1348a9ac51/globalmount" VolumeID="pvc-e7920393-a0e1-45cd-bd8f-1b1348a9ac51" ProjectID=1176226849 HardLimit=10737418240
I0512 15:18:23.764817    3653 publish_unpublish.go:84] "NodePublishVolumeRequest" volumeID="pvc-e7920393-a0e1-45cd-bd8f-1b1348a9ac51" stagingTargetPath="/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-e7920393-a0e1-45cd-bd8f-1b1348a9ac51/globalmount" containerPath="/var/lib/kubelet/pods/25fa1900-9e6f-4e69-81cd-4fa42f8c6faf/volumes/kubernetes.io~csi/pvc-e7920393-a0e1-45cd-bd8f-1b1348a9ac51/mount"
I0512 15:49:53.091863    3653 stage_unstage.go:39] "NodeStageVolumeRequest" volumeID="pvc-dca914b0-83da-409f-8cd6-13b0f711596a" StagingTargetPath="/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-dca914b0-83da-409f-8cd6-13b0f711596a/globalmount"
I0512 15:49:53.105441    3653 quota_linux.go:210] "SetQuota succeeded" Device="/dev/sda3" Path="/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-dca914b0-83da-409f-8cd6-13b0f711596a/globalmount" VolumeID="pvc-dca914b0-83da-409f-8cd6-13b0f711596a" ProjectID=1601122870 HardLimit=10737418240
I0512 15:49:53.125968    3653 publish_unpublish.go:84] "NodePublishVolumeRequest" volumeID="pvc-dca914b0-83da-409f-8cd6-13b0f711596a" stagingTargetPath="/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-dca914b0-83da-409f-8cd6-13b0f711596a/globalmount" containerPath="/var/lib/kubelet/pods/ac5f47a8-3a00-4fea-b3ac-9808f43e4b2d/volumes/kubernetes.io~csi/pvc-dca914b0-83da-409f-8cd6-13b0f711596a/mount"
I0512 15:49:55.388325    3653 stage_unstage.go:39] "NodeStageVolumeRequest" volumeID="pvc-72bd32ed-e6d7-4d31-9ed7-3979a429af99" StagingTargetPath="/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-72bd32ed-e6d7-4d31-9ed7-3979a429af99/globalmount"
I0512 15:49:55.401187    3653 quota_linux.go:210] "SetQuota succeeded" Device="/dev/sda3" Path="/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-72bd32ed-e6d7-4d31-9ed7-3979a429af99/globalmount" VolumeID="pvc-72bd32ed-e6d7-4d31-9ed7-3979a429af99" ProjectID=1767193715 HardLimit=10737418240
I0512 15:49:55.584982    3653 publish_unpublish.go:84] "NodePublishVolumeRequest" volumeID="pvc-72bd32ed-e6d7-4d31-9ed7-3979a429af99" stagingTargetPath="/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-72bd32ed-e6d7-4d31-9ed7-3979a429af99/globalmount" containerPath="/var/lib/kubelet/pods/1709460a-fdbb-42a6-8b80-22009a6c4f3e/volumes/kubernetes.io~csi/pvc-72bd32ed-e6d7-4d31-9ed7-3979a429af99/mount"
I0512 15:50:00.120610    3653 stage_unstage.go:39] "NodeStageVolumeRequest" volumeID="pvc-1196a954-67cf-499b-a79b-4e4026baa4e1" StagingTargetPath="/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-1196a954-67cf-499b-a79b-4e4026baa4e1/globalmount"
I0512 15:50:00.139167    3653 quota_linux.go:210] "SetQuota succeeded" Device="/dev/sda3" Path="/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-1196a954-67cf-499b-a79b-4e4026baa4e1/globalmount" VolumeID="pvc-1196a954-67cf-499b-a79b-4e4026baa4e1" ProjectID=1340016375 HardLimit=10737418240
I0512 15:50:00.384323    3653 publish_unpublish.go:84] "NodePublishVolumeRequest" volumeID="pvc-1196a954-67cf-499b-a79b-4e4026baa4e1" stagingTargetPath="/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-1196a954-67cf-499b-a79b-4e4026baa4e1/globalmount" containerPath="/var/lib/kubelet/pods/d9368641-190a-40d3-9b0c-87ff70df4227/volumes/kubernetes.io~csi/pvc-1196a954-67cf-499b-a79b-4e4026baa4e1/mount"
E0513 06:47:06.699818    3653 leaderelection.go:325] error retrieving resource lock direct-csi-min-io/n01-volume-controller: Get "https://10.96.0.1:443/apis/coordination.k8s.io/v1/namespaces/direct-csi-min-io/leases/n01-volume-controller": context deadline exceeded
I0513 06:47:06.699862    3653 leaderelection.go:278] failed to renew lease direct-csi-min-io/n01-volume-controller: timed out waiting for the condition
E0513 06:47:06.699862    3653 leaderelection.go:325] error retrieving resource lock direct-csi-min-io/n01-drive-controller: Get "https://10.96.0.1:443/apis/coordination.k8s.io/v1/namespaces/direct-csi-min-io/leases/n01-drive-controller": context deadline exceeded
E0513 06:47:06.699875    3653 listener.go:380] stopped leading
I0513 06:47:06.699881    3653 leaderelection.go:278] failed to renew lease direct-csi-min-io/n01-drive-controller: timed out waiting for the condition
E0513 06:47:06.699899    3653 listener.go:380] stopped leading
E0513 06:47:06.699921    3653 event.go:273] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:".16ee9742db9fe9e7", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Lease", Namespace:"", Name:"", UID:"", APIVersion:"coordination.k8s.io/v1", ResourceVersion:"", FieldPath:""}, Reason:"LeaderElection", Message:"n01 stopped leading", Source:v1.EventSource{Component:"n01-drive-controller", Host:""}, FirstTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699876839, time.Local), LastTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699876839, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'can't create an event with namespace 'default' in namespace 'direct-csi-min-io''(may retry after sleeping)
I0513 06:47:06.700000    3653 reflector.go:225] Stopping reflector *v1beta4.DirectCSIDrive (1m0s) from k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167
I0513 06:47:06.700010    3653 listener.go:328] Stopping drive controller
I0513 06:47:06.700075    3653 listener.go:328] Stopping volume controller
I0513 06:47:06.700086    3653 reflector.go:225] Stopping reflector *v1beta4.DirectCSIVolume (1m0s) from k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167
E0513 06:47:06.699905    3653 event.go:273] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:".16ee9742db9f871d", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Lease", Namespace:"", Name:"", UID:"", APIVersion:"coordination.k8s.io/v1", ResourceVersion:"", FieldPath:""}, Reason:"LeaderElection", Message:"n01 stopped leading", Source:v1.EventSource{Component:"n01-volume-controller", Host:""}, FirstTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699851549, time.Local), LastTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699851549, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'can't create an event with namespace 'default' in namespace 'direct-csi-min-io''(may retry after sleeping)
E0513 06:47:06.833396    3653 event.go:273] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:".16ee9742db9f871d", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Lease", Namespace:"", Name:"", UID:"", APIVersion:"coordination.k8s.io/v1", ResourceVersion:"", FieldPath:""}, Reason:"LeaderElection", Message:"n01 stopped leading", Source:v1.EventSource{Component:"n01-volume-controller", Host:""}, FirstTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699851549, time.Local), LastTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699851549, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'can't create an event with namespace 'default' in namespace 'direct-csi-min-io''(may retry after sleeping)
E0513 06:47:15.110642    3653 event.go:273] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:".16ee9742db9fe9e7", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Lease", Namespace:"", Name:"", UID:"", APIVersion:"coordination.k8s.io/v1", ResourceVersion:"", FieldPath:""}, Reason:"LeaderElection", Message:"n01 stopped leading", Source:v1.EventSource{Component:"n01-drive-controller", Host:""}, FirstTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699876839, time.Local), LastTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699876839, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'can't create an event with namespace 'default' in namespace 'direct-csi-min-io''(may retry after sleeping)
E0513 06:47:16.833678    3653 event.go:273] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:".16ee9742db9f871d", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Lease", Namespace:"", Name:"", UID:"", APIVersion:"coordination.k8s.io/v1", ResourceVersion:"", FieldPath:""}, Reason:"LeaderElection", Message:"n01 stopped leading", Source:v1.EventSource{Component:"n01-volume-controller", Host:""}, FirstTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699851549, time.Local), LastTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699851549, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'can't create an event with namespace 'default' in namespace 'direct-csi-min-io''(may retry after sleeping)
E0513 06:47:25.110776    3653 event.go:273] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:".16ee9742db9fe9e7", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Lease", Namespace:"", Name:"", UID:"", APIVersion:"coordination.k8s.io/v1", ResourceVersion:"", FieldPath:""}, Reason:"LeaderElection", Message:"n01 stopped leading", Source:v1.EventSource{Component:"n01-drive-controller", Host:""}, FirstTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699876839, time.Local), LastTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699876839, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'can't create an event with namespace 'default' in namespace 'direct-csi-min-io''(may retry after sleeping)
E0513 06:47:26.834609    3653 event.go:273] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:".16ee9742db9f871d", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Lease", Namespace:"", Name:"", UID:"", APIVersion:"coordination.k8s.io/v1", ResourceVersion:"", FieldPath:""}, Reason:"LeaderElection", Message:"n01 stopped leading", Source:v1.EventSource{Component:"n01-volume-controller", Host:""}, FirstTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699851549, time.Local), LastTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699851549, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'can't create an event with namespace 'default' in namespace 'direct-csi-min-io''(may retry after sleeping)
E0513 06:47:35.110936    3653 event.go:273] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:".16ee9742db9fe9e7", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Lease", Namespace:"", Name:"", UID:"", APIVersion:"coordination.k8s.io/v1", ResourceVersion:"", FieldPath:""}, Reason:"LeaderElection", Message:"n01 stopped leading", Source:v1.EventSource{Component:"n01-drive-controller", Host:""}, FirstTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699876839, time.Local), LastTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699876839, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'can't create an event with namespace 'default' in namespace 'direct-csi-min-io''(may retry after sleeping)
E0513 06:47:36.835616    3653 event.go:273] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:".16ee9742db9f871d", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Lease", Namespace:"", Name:"", UID:"", APIVersion:"coordination.k8s.io/v1", ResourceVersion:"", FieldPath:""}, Reason:"LeaderElection", Message:"n01 stopped leading", Source:v1.EventSource{Component:"n01-volume-controller", Host:""}, FirstTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699851549, time.Local), LastTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699851549, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'can't create an event with namespace 'default' in namespace 'direct-csi-min-io''(may retry after sleeping)
E0513 06:47:40.049830    3653 server.go:92] GRPC error: rpc error: code = NotFound desc = Get "https://10.96.0.1:443/apis/direct.csi.min.io/v1beta4/directcsivolumes/pvc-dca914b0-83da-409f-8cd6-13b0f711596a": http2: client connection lost
E0513 06:47:40.049900    3653 server.go:92] GRPC error: rpc error: code = NotFound desc = Get "https://10.96.0.1:443/apis/direct.csi.min.io/v1beta4/directcsivolumes/pvc-3cf0239f-ae29-4401-9041-0c985646c138": http2: client connection lost
E0513 06:47:40.049931    3653 server.go:92] GRPC error: rpc error: code = NotFound desc = Get "https://10.96.0.1:443/apis/direct.csi.min.io/v1beta4/directcsivolumes/pvc-72bd32ed-e6d7-4d31-9ed7-3979a429af99": http2: client connection lost
E0513 06:47:40.049950    3653 server.go:92] GRPC error: rpc error: code = NotFound desc = Get "https://10.96.0.1:443/apis/direct.csi.min.io/v1beta4/directcsivolumes/pvc-e7920393-a0e1-45cd-bd8f-1b1348a9ac51": http2: client connection lost
E0513 06:47:45.111709    3653 event.go:273] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:".16ee9742db9fe9e7", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Lease", Namespace:"", Name:"", UID:"", APIVersion:"coordination.k8s.io/v1", ResourceVersion:"", FieldPath:""}, Reason:"LeaderElection", Message:"n01 stopped leading", Source:v1.EventSource{Component:"n01-drive-controller", Host:""}, FirstTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699876839, time.Local), LastTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699876839, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'can't create an event with namespace 'default' in namespace 'direct-csi-min-io''(may retry after sleeping)
E0513 06:47:46.836614    3653 event.go:273] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:".16ee9742db9f871d", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Lease", Namespace:"", Name:"", UID:"", APIVersion:"coordination.k8s.io/v1", ResourceVersion:"", FieldPath:""}, Reason:"LeaderElection", Message:"n01 stopped leading", Source:v1.EventSource{Component:"n01-volume-controller", Host:""}, FirstTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699851549, time.Local), LastTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699851549, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'can't create an event with namespace 'default' in namespace 'direct-csi-min-io''(may retry after sleeping)
E0513 06:47:55.112618    3653 event.go:273] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:".16ee9742db9fe9e7", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Lease", Namespace:"", Name:"", UID:"", APIVersion:"coordination.k8s.io/v1", ResourceVersion:"", FieldPath:""}, Reason:"LeaderElection", Message:"n01 stopped leading", Source:v1.EventSource{Component:"n01-drive-controller", Host:""}, FirstTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699876839, time.Local), LastTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699876839, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'can't create an event with namespace 'default' in namespace 'direct-csi-min-io''(may retry after sleeping)
E0513 06:47:56.837751    3653 event.go:273] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:".16ee9742db9f871d", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Lease", Namespace:"", Name:"", UID:"", APIVersion:"coordination.k8s.io/v1", ResourceVersion:"", FieldPath:""}, Reason:"LeaderElection", Message:"n01 stopped leading", Source:v1.EventSource{Component:"n01-volume-controller", Host:""}, FirstTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699851549, time.Local), LastTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699851549, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'can't create an event with namespace 'default' in namespace 'direct-csi-min-io''(may retry after sleeping)
E0513 06:48:05.113679    3653 event.go:273] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:".16ee9742db9fe9e7", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Lease", Namespace:"", Name:"", UID:"", APIVersion:"coordination.k8s.io/v1", ResourceVersion:"", FieldPath:""}, Reason:"LeaderElection", Message:"n01 stopped leading", Source:v1.EventSource{Component:"n01-drive-controller", Host:""}, FirstTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699876839, time.Local), LastTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699876839, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'can't create an event with namespace 'default' in namespace 'direct-csi-min-io''(may retry after sleeping)
E0513 06:48:06.838431    3653 event.go:273] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:".16ee9742db9f871d", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Lease", Namespace:"", Name:"", UID:"", APIVersion:"coordination.k8s.io/v1", ResourceVersion:"", FieldPath:""}, Reason:"LeaderElection", Message:"n01 stopped leading", Source:v1.EventSource{Component:"n01-volume-controller", Host:""}, FirstTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699851549, time.Local), LastTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699851549, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'can't create an event with namespace 'default' in namespace 'direct-csi-min-io''(may retry after sleeping)
E0513 06:48:15.114614    3653 event.go:273] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:".16ee9742db9fe9e7", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Lease", Namespace:"", Name:"", UID:"", APIVersion:"coordination.k8s.io/v1", ResourceVersion:"", FieldPath:""}, Reason:"LeaderElection", Message:"n01 stopped leading", Source:v1.EventSource{Component:"n01-drive-controller", Host:""}, FirstTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699876839, time.Local), LastTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699876839, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'can't create an event with namespace 'default' in namespace 'direct-csi-min-io''(may retry after sleeping)
E0513 06:48:16.839611    3653 event.go:273] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:".16ee9742db9f871d", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Lease", Namespace:"", Name:"", UID:"", APIVersion:"coordination.k8s.io/v1", ResourceVersion:"", FieldPath:""}, Reason:"LeaderElection", Message:"n01 stopped leading", Source:v1.EventSource{Component:"n01-volume-controller", Host:""}, FirstTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699851549, time.Local), LastTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699851549, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'can't create an event with namespace 'default' in namespace 'direct-csi-min-io''(may retry after sleeping)
E0513 06:48:25.115615    3653 event.go:273] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:".16ee9742db9fe9e7", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Lease", Namespace:"", Name:"", UID:"", APIVersion:"coordination.k8s.io/v1", ResourceVersion:"", FieldPath:""}, Reason:"LeaderElection", Message:"n01 stopped leading", Source:v1.EventSource{Component:"n01-drive-controller", Host:""}, FirstTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699876839, time.Local), LastTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699876839, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'can't create an event with namespace 'default' in namespace 'direct-csi-min-io''(may retry after sleeping)
E0513 06:48:26.840612    3653 event.go:273] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:".16ee9742db9f871d", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Lease", Namespace:"", Name:"", UID:"", APIVersion:"coordination.k8s.io/v1", ResourceVersion:"", FieldPath:""}, Reason:"LeaderElection", Message:"n01 stopped leading", Source:v1.EventSource{Component:"n01-volume-controller", Host:""}, FirstTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699851549, time.Local), LastTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699851549, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'can't create an event with namespace 'default' in namespace 'direct-csi-min-io''(may retry after sleeping)
E0513 06:48:35.115894    3653 event.go:273] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:".16ee9742db9fe9e7", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Lease", Namespace:"", Name:"", UID:"", APIVersion:"coordination.k8s.io/v1", ResourceVersion:"", FieldPath:""}, Reason:"LeaderElection", Message:"n01 stopped leading", Source:v1.EventSource{Component:"n01-drive-controller", Host:""}, FirstTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699876839, time.Local), LastTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699876839, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'can't create an event with namespace 'default' in namespace 'direct-csi-min-io''(may retry after sleeping)
E0513 06:48:36.841606    3653 event.go:273] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:".16ee9742db9f871d", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Lease", Namespace:"", Name:"", UID:"", APIVersion:"coordination.k8s.io/v1", ResourceVersion:"", FieldPath:""}, Reason:"LeaderElection", Message:"n01 stopped leading", Source:v1.EventSource{Component:"n01-volume-controller", Host:""}, FirstTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699851549, time.Local), LastTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699851549, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'can't create an event with namespace 'default' in namespace 'direct-csi-min-io''(may retry after sleeping)
E0513 06:48:45.116619    3653 event.go:273] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:".16ee9742db9fe9e7", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Lease", Namespace:"", Name:"", UID:"", APIVersion:"coordination.k8s.io/v1", ResourceVersion:"", FieldPath:""}, Reason:"LeaderElection", Message:"n01 stopped leading", Source:v1.EventSource{Component:"n01-drive-controller", Host:""}, FirstTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699876839, time.Local), LastTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699876839, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'can't create an event with namespace 'default' in namespace 'direct-csi-min-io''(may retry after sleeping)
E0513 06:48:46.843249    3653 event.go:273] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:".16ee9742db9f871d", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Lease", Namespace:"", Name:"", UID:"", APIVersion:"coordination.k8s.io/v1", ResourceVersion:"", FieldPath:""}, Reason:"LeaderElection", Message:"n01 stopped leading", Source:v1.EventSource{Component:"n01-volume-controller", Host:""}, FirstTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699851549, time.Local), LastTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699851549, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'can't create an event with namespace 'default' in namespace 'direct-csi-min-io''(may retry after sleeping)
E0513 06:48:46.843342    3653 event.go:218] Unable to write event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:".16ee9742db9f871d", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Lease", Namespace:"", Name:"", UID:"", APIVersion:"coordination.k8s.io/v1", ResourceVersion:"", FieldPath:""}, Reason:"LeaderElection", Message:"n01 stopped leading", Source:v1.EventSource{Component:"n01-volume-controller", Host:""}, FirstTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699851549, time.Local), LastTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699851549, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}' (retry limit exceeded!)
E0513 06:48:55.117624    3653 event.go:273] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:".16ee9742db9fe9e7", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Lease", Namespace:"", Name:"", UID:"", APIVersion:"coordination.k8s.io/v1", ResourceVersion:"", FieldPath:""}, Reason:"LeaderElection", Message:"n01 stopped leading", Source:v1.EventSource{Component:"n01-drive-controller", Host:""}, FirstTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699876839, time.Local), LastTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699876839, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'can't create an event with namespace 'default' in namespace 'direct-csi-min-io''(may retry after sleeping)
E0513 06:48:55.117703    3653 event.go:218] Unable to write event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:".16ee9742db9fe9e7", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Lease", Namespace:"", Name:"", UID:"", APIVersion:"coordination.k8s.io/v1", ResourceVersion:"", FieldPath:""}, Reason:"LeaderElection", Message:"n01 stopped leading", Source:v1.EventSource{Component:"n01-drive-controller", Host:""}, FirstTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699876839, time.Local), LastTimestamp:time.Date(2022, time.May, 13, 6, 47, 6, 699876839, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}' (retry limit exceeded!)
E0513 08:30:18.829971    3653 server.go:92] GRPC error: rpc error: code = NotFound desc = etcdserver: request timed out
E0513 08:30:39.830640    3653 server.go:92] GRPC error: rpc error: code = NotFound desc = etcdserver: request timed out
E0513 08:30:46.838782    3653 server.go:92] GRPC error: rpc error: code = NotFound desc = etcdserver: request timed out
E0513 08:31:28.846126    3653 server.go:92] GRPC error: rpc error: code = NotFound desc = etcdserver: request timed out
```

running Image:         `quay.io/minio/csi-node-driver-registrar@sha256:d46524376ffccf2c29f2fb373a67faa0d14a875ae01380fa148b4c5a8d47a6c6`

### PR DESCRIPTION
**Pull request by Praveenrajmani**
We perform IOCTL calls to read the smart info serial number of the drive. As a side-effect,
this backfires with too many CHANGE udev events

This PR removes the smart info probe as we already have serial numbers read from udev data.

Fixes #583

### CODE REVIEW

**Review by harshavardhana — APPROVED** [review]

**Review by harshavardhana — APPROVED** [review]

File: pkg/uevent/match.go [hunk 1]
```diff
@@ -56,7 +56,6 @@ var stageOneMatchers = []matchFn{
 	ueventFSUUIDMatcher,
 	// v1beta2 matchers
 	fsUUIDMatcher,
-	serialNumberMatcher,
```
Comment (sinhaashish) [inline pkg/uevent/match.go:59]: Why are we removing this `serialNumberMatcher` . IS it because , yesterday we saw that even if the device are not changed the serial number changes ?

Comment (sinhaashish) [reply pkg/uevent/match.go:59]: If `serialNumberMatcher`  is removed , then its corresponding function `serialNumberMatcher` and test `TestSerialNumberMatcher` must be removed too

Comment (Praveenrajmani) [reply pkg/uevent/match.go:59]: > Why are we removing this serialNumberMatcher 

this probe is not needed as we removed smart serial number probe

> If serialNumberMatcher is removed , then its corresponding function serialNumberMatcher and test TestSerialNumberMatcher must be removed too

such utility functions can be used to write supportability tools for upgrade. so, keeping such functions as is.

Comment (Praveenrajmani) [reply pkg/uevent/match.go:59]: actuall, we can remove. we don't need to rely on smart serial numbers even in future.

**Review by prakashsvmx — APPROVED** [review]
Tested. Changes look good to me :+1:

**Review by sinhaashish — APPROVED** [review]
